-- phpMyAdmin SQL Dump
-- version 4.8.5
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1:3306
-- Generation Time: 05-Nov-2019 às 01:55
-- Versão do servidor: 5.7.26
-- versão do PHP: 7.2.18

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `onware`
--

-- --------------------------------------------------------

--
-- Estrutura da tabela `fornecedor`
--

DROP TABLE IF EXISTS `fornecedor`;
CREATE TABLE IF NOT EXISTS `fornecedor` (
  `id_fornecedor` int(5) NOT NULL AUTO_INCREMENT,
  `marca` varchar(50) NOT NULL,
  `nome` varchar(50) NOT NULL,
  `tipo` varchar(100) NOT NULL,
  `contratacao` date NOT NULL,
  `telefone` bigint(20) NOT NULL,
  `email` varchar(50) NOT NULL,
  `descricao` text CHARACTER SET utf8,
  PRIMARY KEY (`id_fornecedor`)
) ENGINE=MyISAM AUTO_INCREMENT=6 DEFAULT CHARSET=latin1;

--
-- Extraindo dados da tabela `fornecedor`
--

INSERT INTO `fornecedor` (`id_fornecedor`, `marca`, `nome`, `tipo`, `contratacao`, `telefone`, `email`, `descricao`) VALUES
(1, 'NZXT', 'NZXT Brasil', 'Fonte, Gabinete, WaterCooler', '2019-10-25', 18002289395, 'support@nzxt.com', 'NZXT.com Store Returns/Exchange Policy\r\nEligible products qualify for a full refund or exchange only with an authorized RMA number and the item is returned to the NZXT.com Store inventory within 30 days of purchase. Returns are not allowed beyond 30 days of the purchase date.\r\n\r\nThe NZXT.com Store reserves the right to deny any return or exchange. Refunds will be credited to the original method of payment. To initiate a return, simply submit a request at support@nzxt.com.'),
(2, 'Cooler Master', 'Cooler Master Brasil', 'Gabinete, Fonte, WaterCooler, Cooler, Pasta Termica', '2019-10-25', 1150428908, 'rma@coolermaster.com.br', 'As customer satisfaction is a core value of Cooler Master, we would like to notify our customers that our current CRM system is having issues with the ticketing system at this point in time. Once the CRM vendor has verified that the issue has been resolved, we will respond to each and every ticket ASAP. We thank you for your continued patience at this time, and apologize for any inconvenience this issue may cause.'),
(3, 'Corsair', 'Corsair Brasil', 'WaterCooler, Cooler, Fonte, Gabinete', '2019-10-25', 15106578747, 'contato@suporte-corsair.com.br', ''),
(4, 'ONWARE', 'ONWARE BRASIL', 'Computador', '2001-12-20', 45998624155, 'suporte@onware.com.br', ''),
(5, 'fd', 'fd', 'fd', '2001-12-20', 3243567846524233564, 'giuliuscotelo333@teste.com', 'afdsfsfsad');

-- --------------------------------------------------------

--
-- Estrutura da tabela `produto`
--

DROP TABLE IF EXISTS `produto`;
CREATE TABLE IF NOT EXISTS `produto` (
  `id_produto` int(5) NOT NULL AUTO_INCREMENT,
  `marca` varchar(20) DEFAULT NULL,
  `modelo` varchar(50) DEFAULT NULL,
  `tipo` varchar(50) DEFAULT NULL,
  `preco` varchar(10) DEFAULT NULL,
  `quantidade` int(4) NOT NULL DEFAULT '1',
  `imagem` varchar(50) NOT NULL,
  `descricao` text,
  PRIMARY KEY (`id_produto`)
) ENGINE=MyISAM AUTO_INCREMENT=47 DEFAULT CHARSET=utf8;

--
-- Extraindo dados da tabela `produto`
--

INSERT INTO `produto` (`id_produto`, `marca`, `modelo`, `tipo`, `preco`, `quantidade`, `imagem`, `descricao`) VALUES
(2, 'Corsair', 'ML120 PRO', 'Cooler', '80,00', 1, 'COOLER_CORSAIR_ML120PRO.png', 'A ML120 PRO da Corsair oferece um desempenho e silÃªncio incomparÃ¡veis por meio da tecnologia de levitaÃ§Ã£o magnÃ©tica e de um design personalizado de rotor. O design inovador fornece alta pressÃ£o estÃ¡tica e elevado fluxo de ar.\r\n\r\nFan Warranty Five years\r\nFan Size 120mm x 25mm\r\nBearing Type Magnetic Levitation\r\nFlow Type Static Pressure\r\nLED Color None\r\nOperating Voltage 10.8V - 13.2V\r\nPWM Control YES\r\nCORSAIR iCUE Compatibility NO\r\nFan Model ML Series\r\n\r\nPackage Quantity Single Fan\r\nSpeed 400 - 2400 RPM\r\nSound Level 37 dBA\r\nPower Draw 0.225 A\r\nStatic Pressure 0.2 - 4.2 mmH20\r\nFan Airflow 75 CFM'),
(3, 'Corsair', 'ML140 PRO RGB', 'Cooler', '110,00', 1, 'COOLER_CORSAIR_ML140PRORGB.png', 'A ventoinha PWM ML140 PRO RGB da CORSAIR com iluminaÃ§Ã£o RGB vibrante, controlada pelo software CORSAIR iCUE, oferece desempenho e operaÃ§Ã£o com baixo ruÃ­do incomparÃ¡veis utilizando a tecnologia de rolamento de levitaÃ§Ã£o magnÃ©tica.\r\n\r\nFan Warranty Five years\r\nFan Size 140mm x 25mm\r\nBearing Type Magnetic Levitation\r\nFlow Type Static Pressure\r\nLED Color RGB\r\nOperating Voltage 10.8V - 13.2V\r\nPWM Control YES\r\nCORSAIR iCUE Compatibility YES\r\nFan Model ML Series\r\n \r\nWeight 0.47\r\nPackage Quantity 2\r\nSpeed 400 - 1200 RPM\r\nSound Level 20.4 dBA\r\nPower Draw 0.2 A\r\nStatic Pressure 1.27 mm-H2O\r\nAdaptive Sync RGB\r\nFan Airflow 55.4 CFM'),
(4, 'Corsair', '280X BLACK', 'Gabinete', '500,00', 1, 'GABINETE_CORSAIR_280XBLACK.png', 'O CORSAIR Crystal Series 280X Ã© um gabinete Micro-ATX de alto desempenho com trÃªs lindos painÃ©is em vidro temperado e um layout interno inovador com duas cÃ¢maras que facilita a montagem de sistemas organizados e com resfriamento superior.\r\n\r\nCase Dimensions 398mm x 276mm x 351mm\r\nMaximum GPU Length 300mm\r\nMaximum PSU Length 180mm\r\nMaximum CPU Cooler Height 150mm\r\nCase Expansion Slots 4\r\nCase Drive Bays â€(x2) 3.5in (x3) 2.5inâ€\r\nCase Form Factor MicroATX\r\nCase Windowed Tempered Glass\r\nCase Warranty Two years\r\niCUE enabled No\r\n\r\nCase Material Steel, Tempered Glass\r\nRadiator Compatibility 120mm, 140mm, 240mm, 280mm\r\nCompatible Corsair Liquid Coolers H55, H60, H75, H80i, H90, H100i, H105, H110i, H115i\r\nCase Power Supply ATX (not included)\r\nWeight 7.1kg / 15.65 lbs\r\nCase Drive Bays 3.5\" 2\r\nCase Drive Bays 2.5\" 3'),
(5, 'Corsair', '280X WHITE RGB', 'Gabinete', '700,00', 1, 'GABINETE_CORSAIR_280XWHITERGB.png', 'O CORSAIR Crystal Series 280X RGB Ã© um gabinete Micro-ATX de alto desempenho com trÃªs lindos painÃ©is em vidro temperado, iluminaÃ§Ã£o RGB e um layout interno inovador com duas cÃ¢maras que facilita a montagem de sistemas mais sofisticados e organizados.\r\n\r\nCase Dimensions 398mm x 276mm x 351mm\r\nMaximum GPU Length 300mm\r\nMaximum PSU Length 180mm\r\nMaximum CPU Cooler Height 150mm\r\nCase Expansion Slots 4\r\nCase Drive Bays â€(x2) 3.5in (x3) 2.5inâ€\r\nCase Form Factor MicroATX\r\nCase Windowed Tempered Glass\r\nCase Warranty Two years\r\niCUE enabled Yes\r\n\r\nCase Material Steel, Tempered Glass\r\nRadiator Compatibility 120mm, 140mm, 240mm, 280mm\r\nCompatible Corsair Liquid Coolers H55, H60, H75, H80i, H90, H100i, H105, H110i, H115i\r\nCase Power Supply ATX (not included)\r\nWeight 7.1kg / 15.65 lbs\r\nLighting RGB\r\nCase Drive Bays 3.5\" 2\r\nCase Drive Bays 2.5\" 3'),
(6, 'NZXT', 'H510 Elite', 'Gabinete', '600,00', 1, 'GABINETE_NZXT_H510ELITE.png', 'Dimensions	W: 210mm H: 435mm D: 428mm (without feet)\r\nW: 210mm H: 460mm D: 428mm (with feet)\r\nMaterial(s)	SGCC Steel, Tempered Glass\r\nWeight	7.5 kg\r\nClearance	Cable Management: 19-23mm\r\nGPU Clearance: Up to 368.6mm w/o front radiator installed, up to 313.6mm with front radiator installed\r\nVertical GPU Mount Clearance: 40.64mm\r\nCPU Cooler: Up to 165mm\r\nFront Radiator: 60mm\r\nRear Radiator: 60mm\r\nReservoir & Pump: Up to 180mm (Along cable bar), Up to 86mm (Along bottom panel)\r\nMotherboard Support	Mini-ITX, MicroATX, ATX\r\nFront I/O Ports	1x USB 3.1 Gen 2 Type-C\r\n1x USB 3.1 Gen 1 Type-A\r\n1x Headset Audio Jack\r\nFront I/O internal header\r\n1x USB 3.1 Gen 2 Internal Header\r\n1x USB 3.1 Gen 1 Internal Header\r\n1x USB 2.0 Internal Header\r\n1x HD Audio Header\r\nFilters	All Air Intakes\r\nSmart Device V2	3x Fan channels with Max 10W per channel output*\r\n2x RGB LED channels, each support up to 4x HUE 2 addressable LED strips or 5x Aer RGB 2 fans\r\nBuilt-in noise detection module\r\n*Note : If a splitter is used, fan control is regulated depending on the fan connected to the 4-pin port . Do not use low-noise adapters.\r\nRGB LED Lighting	2x Integrated Aer RGB 2 140mm Fans\r\n1x Integrated addressable LED Strip\r\nVertical GPU Mount	2 Slots\r\nDrive Bays	2.5\": 2+1\r\n3.5\": 2+1\r\nExpansion Slots	7\r\nRadiator Support	Front: 2x 140 or 2x 120mm with Pull\r\n*Note: Need to remove RGB fans if you plan to mount the radiator to the front\r\nRear: 1x 120mm\r\nFan Support	Front: 2x 120/ 2x 140mm (2x AER RGB 2 140mm included)\r\nTop: 1x 120mm/ 1x 140mm (1x AER F140 Case Version Included)\r\nRear: 1x 120mm (1x AER F120 Case Version Included)\r\nFan Specs	Aer RGB 2 (140mm)\r\nSpeed: 500-1,500 RPM\r\nAirflow: 30.39 - 91.19 CFM\r\nNoise: 22 - 33 dBA\r\nAir Pressure: 0.17 â€“ 1.52mm-H2O\r\nBearing: Fluid Dynamic Bearing\r\nFan Connector 4-Pin PWM\r\nWarranty	2 Years'),
(7, 'NZXT', 'H710i', 'Gabinete', '600,00', 1, 'GABINETE_NZXT_H710I.png', 'Dimensions	W: 230mm H: 516mm D: 494mm (with feet)\r\nMaterial(s)	SGCC Steel and Tempered Glass\r\nWeight	12.3 kg\r\nMotherboard Support	Mini-ITX, MicroATX, ATX and EATX (Up to 272mm or 10.7-inches)\r\nFront I/O Ports	1x USB 3.1 Gen 2 Type-C\r\n2x USB 3.1 Gen 1 Type-A\r\n1x Headset Audio Jack\r\nFront I/O internal header\r\n1x USB 3.1 Gen 2 Internal Header\r\n1x USB 3.1 Gen 1 Internal Header\r\n1x USB 2.0 Internal Header\r\n1x HD Audio Header\r\nFilters	All Air Intakes\r\nSmart Device V2	3x Fan channels with Max 10W per channel output*\r\n2x RGB LED port support up to 4 x HUE 2 addressable LED strips or 5 x Aer RGB fans\r\nBuilt-in noise detection module\r\n*Note: If a splitter is used, fan control is regulated depending on the fan connected to the 4-pin port. Do not use low-noise adapters.\r\nLED Strip(s)	2 integrated addressable LED strips\r\nVertical GPU Mount	Up to 2.5 Slots\r\nIncluded Accessories	Installation screws\r\n10x Cable ties\r\n1x Headset Audio Jack Splitter (4 pole to 3 pole)\r\nExpansion Slots	7\r\nDrive Bays	2.5â€: 7\r\n3.5â€: 2+2\r\nRadiator Support	Front: 2x 140 or 3x 120mm with Push/Pull\r\nTop: 2x 140 or 3x 120\r\nRear: 1x 120\r\nFan Support	Front: 3x 120/ 2x 140mm (3 Aer F120 Case Version included)\r\nTop: 3x 120/2x 140mm\r\nRear: 1x 120/1x 140mm (1 Aer F140 Case Version included)\r\nFan Specs	Aer F120 (Case Version)\r\nSpeed: 1200 Â± 200 RPM\r\nAirflow: 50.42\r\nCFM Noise: 28 dBA\r\nBearing: Rifle Bearing\r\nAer F140 (Case Version)\r\nSpeed: 1,000 Â± 200 RPM\r\nAirflow: 68.95 CFM\r\nNoise: 29 dBA\r\nBearing: Rifle Bearing\r\nClearance	Cable Management: 18-22mm\r\nGPU Clearance: Up to 413mm\r\nVertical GPU Mount Clearance: 50.8mm\r\nCPU Cooler: Up to 185mm\r\nFront Radiator: 60mm\r\nTop Radiator: 30mm\r\nReservoir & Pump: Up to 224mm (Along cable bar)\r\nWarranty	2 Years'),
(8, 'NZXT', 'H210i', 'Gabinete', '300,00', 1, 'GABINETE_NZXT_H210I.png', 'Dimensions	W: 210mm H: 349mm D: 372mm (with feet)\r\nMaterial(s)	SGCC Steel and Tempered Glass\r\nWeight	6 kg\r\nMotherboard Support	Mini-ITX\r\nFront I/O Ports	1x USB 3.1 Gen 1 Type-A\r\n1x USB 3.1 Gen 2 Type-C\r\n1x Headset Audio Jack\r\nFront I/O internal header\r\n1x USB 3.1 Gen 2 Internal Header\r\n1x USB 3.1 Gen 1 Internal Header\r\n1x USB 2.0 Internal Header\r\n1x HD Audio Header\r\nFilters	All Air Intakes\r\nSmart Device V2	3x Fan channels with Max 10W per channel output*\r\n2x RGB LED port support up to 4x HUE 2 addressable LED strips or 5x Aer RGB or Aer RGB 2 fans\r\nBuilt-in noise detection module\r\n*Note: If a splitter is used, fan control is regulated depending on the fan connected to the 4-pin port. Do not use low-noise adapters.\r\nLED Strip(s)	1 integrated addressable LED strip\r\nIncluded Accessories	Installation screws\r\n10 x Cable ties\r\n1x Headset Audio Jack splitter (4 pole to 3 pole)\r\n1x GPU stand\r\nExpansion Slots	2\r\nDrive Bays	2.5\": 3+1\r\n3.5\": 1\r\nRadiator Support	Front: 2x 120mm with Push or Pull\r\nRear: 1x 120mm\r\nFan Support	Front: 2x 120 / 2x 140mm\r\nTop: 1x 120mm (1 AER F120 Case version included)\r\nRear: 1x 120mm (1 AER F120 Case version included)\r\nFan Specs	Aer F120 (Case Version)\r\nSpeed: 1200 Â± 200 RPM\r\nAirflow: 50.42\r\nCFM Noise: 28 dBA\r\nBearing: Rifle Bearing\r\nClearance	Cable Management: 16.3mm\r\nGPU Clearance: Up to 325mm\r\nGPU Max Thickness: 44mm\r\nCPU Cooler: Up to 165mm\r\nFront Radiator: 85mm\r\nRear Radiator: 42mm\r\nPSU Length: 311mm\r\nWarranty	2 years'),
(9, 'NZXT', 'H700 PUBG', 'Gabinete', '2000,00', 1, 'GABINETE_NZXT_H700PUBG.png', 'Dimensions	W: 230mm H: 494mm D: 494mm (without feet)\r\nW: 230mm H: 516mm D: 494mm (with feet)\r\nMaterial(s)	SECC Steel and Tempered Glass\r\nWeight	12.3 kg\r\nMotherboard Support	Mini-ITX, MicroATX, ATX and EATX(Up to 272mm or 10.7-inches)\r\nI/O Ports	2 x USB 2.0\r\n2 x USB 3.1 Gen 1\r\n1 x Audio/Mic\r\nFilters	Front and PSU Intake\r\nSmart Device	Not included. See H700i.\r\nExpansion Slots	7\r\nDrive Bays	2.5â€: 7\r\n3.5â€: 2+1\r\nRadiator Support	Front: 2 x 140 or 3 x 120mm with Push/Pull\r\nTop: 2 x 140 or 3 x 120\r\nRear: 1 x 120\r\nFan Support	Front: 3 x 120/2 x 140mm (3 Aer F120 Case Version included)\r\nTop: 3 x 120/2 x 140mm\r\nRear: 1 x 120/1 x 140mm (1 Aer F140 Case Version included)\r\nFan Specs	Aer F120 (Case Version)\r\nSpeed: 1200 + 200 RPM\r\nAirflow: 50.42\r\nCFM Noise: 28 dBA\r\nBearing: Rifle Bearing\r\nAer F140 (Case Version)\r\nSpeed: 1,000 + 200 RPM\r\nAirflow: 68.95 CFM\r\nNoise: 29 dBA\r\nBearing: Rifle Bearing\r\nClearance	Cable Management: 18-22mm\r\nGPU Clearance: Up to 413mm\r\nCPU Cooler: Up to 185mm\r\nFront Radiator: 60mm\r\nTop Radiator: 30mm\r\nReservoir & Pump: Up to 224mm (Along cable bar)\r\nWarranty	2 Years'),
(10, 'NZXT', 'KRAKEN X72', 'WaterCooler', '700,00', 1, 'WATERCOOLER_NZXT_KRAKENX72.png', 'The all-new Kraken Series features the most advanced controls ever to be included in an all-in-one liquid cooler. Through CAMâ€™s software interface, users can fine-tune settings to ensure an optimal performance, even in the most intense gaming sessions. Everything, including the pump, radiator, and the fans, have been redesigned to bring you the greatest experience in liquid cooling, all backed by an industry-leading 6-year warranty.\r\n\r\nDimensions	Radiator: 394 x 120 x 27mm\r\nPump: 80 x 80 x 52.9mm\r\nMaterial(s)	Aluminum, copper, plastic, ultra-low evaporation rubber, nylon sleeving\r\nWeight	1.29 Kg\r\nCPU & Socket	Intel Socket 1151, 1150, 1155, 1156, 1366, 2011, 2011-3, 2066\r\nAMD SocketTR4, AM4, FM2+, FM2, FM1, AM3+, AM3, AM2+, AM2\r\nRAM Height Clearance	35mm\r\nControl Modes	Fan: Silent / Performance / Custom / Manual\r\nPump: Silent / Performance / Custom / Manual\r\nLED Modes	Preset Modes: Fixed, Breathing, Fading, Marquee, Covering Marquee, Pulse, Spectrum Wave, Alternating, Tai Chi, Water Cooler, Loading\r\nReactive Modes: Smart and Audio\r\nPump Speed	1,600~2,800 +/- 300RPM\r\nFan Model	Aer P120\r\nNumber of Fans	3\r\nFan Speed	500-2,000 +/- 300 RPM\r\nFan Noise Level	21-36dBA\r\nWarranty	6 years'),
(12, 'NZXT', 'KRAKEN X62', 'WaterCooler', '500,00', 1, 'WATERCOOLER_NZXT_KRAKENX62.png', 'The all-new Kraken Series features the most advanced controls ever to be included in an all-in-one liquid cooler. Through CAMâ€™s software interface, users can fine-tune settings to ensure an optimal performance, even in the most intense gaming sessions. Everything, including the pump, radiator, and the fans, have been redesigned to bring you the greatest experience in liquid cooling, all backed by an industry-leading 6-year warranty. \r\n\r\nDimensions	Radiator: 315 x 143 x 30mm\r\nPump: 80 x 80 x 52.9mm\r\nMaterial(s)	Aluminum, copper, plastic, ultra-low evaporation rubber, nylon sleeving\r\nWeight	1.29kg\r\nCPU & Socket	Intel Socket 1151, 1150, 1155, 1156, 1366, 2011, 2011-3, 2066\r\nAMD SocketTR4, AM4, FM2+, FM2, FM1, AM3+, AM3, AM2+, AM2\r\nRAM Height Clearance	35mm\r\nControl Modes	Fan: Silent / Performance / Custom / Manual\r\nPump: Silent / Performance / Custom / Manual\r\nControl Method	Software with CAM\r\nLED Modes	Preset Modes: Fixed, Breathing, Fading, Marquee, Covering Marquee, Pulse, Spectrum Wave, Alternating, Tai Chi, Water Cooler, Loading\r\nReactive Modes: Smart and Audio\r\nPump Speed	1,600~2,800 +/- 300RPM\r\nFan Model	Aer P140\r\nNumber of Fans	2\r\nFan Speed	500~1,800 +/- 300RPM\r\nFan Noise Level	21-38dBA\r\nWarranty	6 years'),
(13, 'NZXT', 'E850', 'Fonte', '600,00', 1, 'FONTE_NZXT_E850.png', 'The new E Series ATX power supplies from NZXT feature digital voltage and temperature monitoring so you get precise, real-time information about your PSU, including uptime, wattage by rail, and temperature. Store and track key data over time using CAM so youâ€™ll always have an accurate picture of your PSUâ€™s health. Manufactured with top-quality components and backed by a 10-year warranty, the E850 delivers both peace of mind and up to 850 watts of clean, reliable power to your multi-GPU gaming system.\r\n\r\nDimensions	150 x 150 x 86 mm\r\nMaterial(s)	Steel, PCB and plastic\r\nCompliance Standard	ATX12V v2.4 / EPS12V v2.92\r\nPF Correction	Active@0.99\r\nAC Input Rating	100-240Vac, 12-6A, 50-60Hz\r\nFan Specs	Dimensions: 120 x 120 x 25mm\r\nSpeed: 0-1,800 + 180 RPM\r\nAirflow: 73.9 CFM\r\nNoise: 32.3 dBA\r\nBearing: FDB (Fluid Dynamic Bearing)\r\nHazardous Materials	RoHS & China RoHS\r\nEnergy Efficiency	80 Plus Gold 20% loading: 87%, 50% loading: 90%, 100% loading: 87% @115Vac\r\nOperation Temperature	0 to 50Â°C\r\nRegulations & Certifications (EMC & Safety)	CB / CE / FCC / TUV / cTUV-SUDus / China CCC / Taiwan BSMI / Australia RCM / EAC\r\nMTBF	100,000 hours\r\nOutput Connector(s)	1 x 24-pin ATX power\r\n2 x 4+4-pin CPU power\r\n6 x PCIe (6+2 pin)\r\n8 x SATA\r\n6 x Peripherals\r\n1 x Mini-USB\r\nIncluded Cables	1 x 24-pin ATX power (length: 610 mm, Nylon sleeving)\r\n2 x 4+4-pin CPU power (length: 650 mm, Nylon sleeving)\r\n3 x PCIe (6+2 pin) (length: 675 +75 mm, Nylon sleeving)\r\n2 x SATA (length: 500 + 100 +100 +100 mm)\r\n2 x Peripherals (length: 500 + 100 +100 mm)\r\n1 x Mini-USB (length: 600mm)\r\nWarranty	10 years'),
(14, 'NZXT', 'E650', 'Fonte', '450,00', 1, 'FONTE_NZXT_E650.png', 'The new E Series ATX power supplies from NZXT feature digital voltage and temperature monitoring so you get precise, real-time information about your PSU, including uptime, wattage by rail, and temperature. Store and track key data over time using CAM so youâ€™ll always have an accurate picture of your PSUâ€™s health. Manufactured with top-quality components and backed by a 10-year warranty, the E650 delivers both peace of mind and up to 650 watts of clean, reliable power to your multi-GPU gaming system.\r\n\r\nDimensions	150 x 150 x 86 mm\r\nMaterial(s)	Steel, PCB and plastic\r\nCompliance Standard	ATX12V v2.4 / EPS12V v2.92\r\nPF Correction	Active@0.99\r\nAC Input Rating	100-240Vac, 9-4.5A, 50-60Hz\r\nFan Specs	Dimensions: 120 x 120 x 25mm\r\nSpeed: 0-1,800 + 180 RPM\r\nAirflow: 73.9 CFM\r\nNoise: 32.3 dBA\r\nBearing: FDB (Fluid Dynamic Bearing)\r\nHazardous Materials	RoHS & China RoHS\r\nEnergy Efficiency	80 Plus Gold 20% loading: 87%, 50% loading: 90%, 100% loading: 87% @115Vac\r\nOperation Temperature	0 to 50Â°C\r\nRegulations & Certifications (EMC & Safety)	CB / CE / FCC / TUV / cTUV-SUDus / China CCC / Taiwan BSMI / Australia RCM / EAC\r\nMTBF	100,000 hours\r\nOutput Connector(s)	1 x 24-pin ATX power\r\n1 x 4+4-pin CPU power\r\n4 x PCIe (6+2 pin)\r\n8 x SATA\r\n6 x Peripherals\r\n1 x Mini-USB\r\nIncluded Cables	1 x 24-pin ATX power (length: 610 mm, Nylon sleeving)\r\n1 x 4+4-pin CPU power (length: 650 mm, Nylon sleeving)\r\n2 x PCIe (6+2 pin) (length: 675 +75 mm, Nylon sleeving)\r\n2 x SATA (length: 500 + 100 +100 +100 mm)\r\n2 x Peripherals (length: 500 + 100 +100 mm)\r\n1 x Mini-USB (length: 600mm)\r\nWarranty	10 years'),
(15, 'NZXT', 'E500', 'Fonte', '300,00', 1, 'FONTE_NZXT_E500.png', 'The new E Series ATX power supplies from NZXT feature digital voltage and temperature monitoring so you get precise, real-time information about your PSU, including uptime, wattage by rail, and temperature. Store and track key data over time using CAM so youâ€™ll always have an accurate picture of your PSUâ€™s health. Manufactured with top-quality components and backed by a 10-year warranty, the E500 delivers both peace of mind and up to 500 watts of clean, reliable power to your single GPU gaming system.\r\n\r\nDimensions	150 x 150 x 86 mm\r\nMaterial(s)	Steel, PCB and plastic\r\nCompliance Standard	ATX12V v2.4 / EPS12V v2.92\r\nPF Correction	Active@0.99\r\nAC Input Rating	100-240Vac, 8-4A, 50-60Hz\r\nFan Specs	Dimensions: 120 x 120 x 25mm\r\nSpeed: 0-1,800 + 180 RPM\r\nAirflow: 73.9 CFM\r\nNoise: 32.3 dBA\r\nBearing: FDB (Fluid Dynamic Bearing)\r\nHazardous Materials	RoHS & China RoHS\r\nEnergy Efficiency	80 Plus Gold 20% loading: 87%, 50% loading: 90%, 100% loading: 87% @115Vac\r\nOperation Temperature	0 to 50Â°C\r\nRegulations & Certifications (EMC & Safety)	CB / CE / FCC / TUV / cTUV-SUDus / China CCC / Taiwan BSMI / Australia RCM / EAC\r\nMTBF	100,000 hours\r\nOutput Connector(s)	1 x 24-pin ATX power\r\n1 x 4+4-pin CPU power\r\n2 x PCIe (6+2 pin)\r\n8 x SATA\r\n3 x Peripherals\r\n1 x Mini-USB\r\nIncluded Cables	1 x 24-pin ATX power (length: 610 mm, Nylon sleeving)\r\n1 x 4+4-pin CPU power (length: 650 mm, Nylon sleeving)\r\n1 x PCIe (6+2 pin) (length: 675 +75 mm, Nylon sleeving)\r\n2 x SATA (length: 500 + 100 +100 +100 mm)\r\n1 x Peripherals (length: 500 + 100 +100 mm)\r\n1 x Mini-USB (length: 600mm)\r\nWarranty	10 years'),
(16, 'Cooler Master', 'SL600M', 'Gabinete', '770,00', 1, 'GABINETE_COOLERMASTER_SL600M.png', 'WORK/PLAY\r\nAnodized Aluminum Panels\r\nVertical Layout & Chimney Effect\r\nAcoustic Noise Reduction\r\nOperational Noise Reduction\r\nRotatable PCI Bracket\r\nVersatile Storage Brackets\r\nProximity Lighting & I/O Panel\r\nAdjustable Top Ventilation\r\n\r\nAVAILABLE COLOR(S)\r\nBlack, Silver\r\nMATERIALS\r\nSteel body, Front Panel - Aluminum, Top Panel - Aluminum, Left Side Panel - Tempered Glass, Right Side Panel - Steel\r\nDIMENSIONS (LXWXH)\r\n544 x 242 x 574mm\r\nMOTHERBOARD SUPPORT\r\nMini ITX, Micro ATX, ATX\r\nEXPANSION SLOTS\r\n9+2\r\n5.25\" DRIVE BAYS\r\n0\r\n2.5\" / 3.5\" DRIVE BAYS (COMBO)\r\n4\r\nDRIVE BAYS - SSD\r\n4\r\nI/O PORT - POWER-LED COLOR\r\nWhite\r\nI/O PORT - HDD-LED COLOR\r\nWhite\r\nI/O PORT - USB-PORTS\r\n1x USB 3.1 Type C, 2x USB 3.0 Type A, 2x USB 2.0 Type A\r\nI/O PORT - AUDIO IN/OUT\r\n1x 3.5mm Headset Jack (Audio+Mic), 1x 3.5mm Mic Jack\r\nFAN CONTROL\r\n4 step slide, 4 pin PWM x 4\r\nPRE-INSTALLED FANS - BOTTOM\r\n200mm PWM Fan x 2 (Speed: 400~800RPM / Connector: 4Pin)\r\nFAN SUPPORT - TOP\r\n3x 120mm, 2x 140/200mm\r\nFAN SUPPORT - BOTTOM\r\n3x 120mm, or 2x 140/200mm\r\nRADIATOR SUPPORT - TOP\r\n120mm, 140mm, 240mm, 280mm, 360mm\r\nRADIATOR SUPPORT - BOTTOM\r\n120mm, 140mm, 240mm, 360mm (maximum thickness clearance 72mm when the GFX is installed in the vertical position)\r\nCLEARANCE - CPU COOLER\r\n191mm\r\nCLEARANCE - PSU\r\n200mm/7.87\"\r\nCLEARANCE - GFX\r\n318mm\r\nDUST FILTERS\r\nBottom\r\nPOWER SUPPLY SUPPORT\r\nFront Top Mount, ATX\r\nEAN CODE\r\n4719512075135\r\nUPC CODE\r\n884102047626\r\nSERIES\r\nMasterCase Series\r\nSIZE\r\nMid Tower'),
(17, 'Cooler Master', 'HYPER 212', 'CPU Cooler', '150,00', 1, 'CPUCOOLER_COOLERMASTER_HYPER212.png', 'The legendary Hyper air cooler is back and better than before. The Hyper 212 Black Edition offers better installation and great performance, easily one of the best air cooling solutions. The aluminum top cover and nickel plated jet black fins give the Hyper 212 Black Edition a more premium exterior appeal . The sleek jet black not only makes it look great, but also increase cooling performance.\r\n\r\nCPU SOCKET\r\nLGA2066, LGA2011-v3, LGA2011, LGA1151, LGA1150, LGA1155, LGA1156, LGA1366, AM4, AM3+, AM3, AM2+, AM2, FM2+, FM2, FM1\r\nDIMENSIONS (L X W X H)\r\n120 x 79.6 x 158.8 mm / 4.7 x 3.1 x 6.3 inch\r\nHEAT SINK MATERIAL\r\n4 Heat Pipes, Aluminum Fins, Direct Contact\r\nFAN DIMENSIONS (L X W X H)\r\n120 x 120 x 25mm\r\nFAN QUANTITY\r\n1 PCS\r\nFAN SPEED\r\n650-2000 RPM (PWM) Â± 10%\r\nFAN AIRFLOW\r\n42 CFM (Max)\r\nFAN AIR PRESSURE\r\n2.9 mmH2O\r\nFAN MTTF\r\n160,000 Hours\r\nFAN NOISE LEVEL\r\n6.5 - 26 dBA\r\nFAN POWER CONNECTOR\r\n4-Pin (PWM)\r\nFAN RATED VOLTAGE\r\n12V DC\r\nFAN RATED CURRENT\r\n0.08 A\r\nFAN SAFETY CURRENT\r\n0.16A\r\nFAN POWER CONSUMPTION\r\n0.96 W\r\nWARRANTY\r\n2 years\r\nCOOLER TYPE\r\nAir Cooler\r\nSERIE\r\nHyper'),
(18, 'Cooler Master', 'MasterFan PRO 140 Air Pressure', 'Cooler', '90,00', 1, 'COOLER_COOLERMASTER_MFPRO140AP.png', 'MASTERFAN PRO 140 AIR PRESSURE\r\nSELECT YOUR SILENCE\r\nHeli-Inspired\r\nSpeed Profiles\r\nQuiet Spin\r\nNoise Absorption\r\nJam Protection\r\n\r\nLED\r\nNon-LED\r\nFAN DIMENSIONS (L X W X H)\r\n140 x 140 x 25 mm / 5.5 x 5.5 x 1 inch\r\nFAN SPEED\r\n650-1550 RPM Â± 10% - S Mode (Silent), 650-2200 RPM Â± 10% - Q Mode (Quiet), 650-2800 RPM Â± 10% - P Mode (Performance)\r\nFAN AIRFLOW\r\n46.2 CFM Â± 10% - S Mode (Silent), 64.2 CFM Â± 10% - Q Mode (Quiet), 82.2 CFM Â± 10% - P Mode (Performance)\r\nFAN AIR PRESSURE\r\n1.59 mmH2O Â± 10% - S Mode (Silent), 3.15 mmH2O Â± 10% - Q Mode (Quiet), 5.28 mmH2O Â± 10% - P Mode (Performance)\r\nFAN LIFE EXPECTANCY\r\n490,000 Hours\r\nFAN NOISE LEVEL\r\n6-20 dBA - S Mode (Silent), 6-30 dBA - Q Mode (Quiet), 6-36 dBA - P Mode (Performance)\r\nFAN POWER CONNECTOR\r\n4-Pin (PWM)\r\nFAN RATED VOLTAGE\r\n12V DC\r\nFAN RATED CURRENT\r\n0.09A - S Mode (Silent), 0.15A - Q Mode (Quiet), 0.25A - P Mode (Performance)\r\nFAN POWER CONSUMPTION\r\n1.08W - S Mode (Silent), 1.8W - Q Mode (Quiet), 3W - P Mode (Performance)\r\nFAN WEIGHT\r\n172g\r\nACCESSORY\r\n4x Tap Screw\r\nWARRANTY\r\n5 years\r\nSERIE\r\nMasterFan Pro\r\nCOOLER TYPE\r\nCase Fan'),
(19, 'Cooler Master', 'MASTERWATT MAKER 1500 PLUS', 'Fonte', '1300,00', 1, 'FONTE_COOLERMASTER_MWM1500PLUS.png', 'MASTERWATT MAKER 1500 PLUS\r\nFULL MODULAR DIGITAL 80 PLUS TITANIUM CERTIFIED POWER SUPPLY\r\nDIGITAL POWER SUPPLY\r\nMASTERPLUS+ SOFTWARE\r\nSILENCIO 135MM LDB FAN\r\nFULL-MODULAR, HIGH CAPACITY CABLES\r\n80 PLUS TITANIUM EFFICIENCY\r\n7 YEAR WARRANTY\r\n\r\n\r\nFull Modular\r\nPOWER\r\n1500 Watts\r\nATX VERSION\r\nATX 12V, fully modular\r\nPFC\r\nActive PFC (>0.95 typical)\r\nINPUT VOLTAGE\r\n100-240V\r\nINPUT CURRENT\r\n15-7.5A\r\nINPUT FREQUENCY\r\n47-63Hz\r\nDIMENSIONS (L X W X H)\r\n200 x 150 x 86 mm\r\nFAN SIZE\r\n135mm Silencio FP Fan\r\nPOWER GOOD SIGNAL\r\n100-500ms\r\nHOLD UP TIME\r\n16ms\r\nEFFICIENCY\r\n90-94%\r\nMTBF\r\n100,000 Hours\r\nPROTECTIONS\r\nOPP, OVP, OCP, SCP, OTP\r\nREGULATORY\r\nTUV, CE, FCC, BSMI, EAC, RCM, CCC, KC\r\nMB 20+4 PIN CONNECTORS\r\n1\r\nCPU 12V 4+4 PIN CONNECTORS\r\n2\r\nPCI-E 6+2 PIN CONNECTORS\r\n12\r\nSATA CONNECTORS\r\n20\r\nPERIPHERAL 4-PIN CONNECTORS\r\n12\r\nFDD CABLE 4-PIN CONNECTORS\r\n1\r\nSERIE\r\nMasterWatt Maker Series\r\nPRODUCT NAME\r\nMasterWatt Maker 1500 Plus\r\nWATTAGE\r\nAbove 750W\r\n80 PLUS\r\nTitanium'),
(20, 'Cooler Master', 'SILENCIO S400', 'Gabinete', '270,00', 1, 'GABINTE_COOLERMASTER_SILENCIOS400.png', 'SILENCIO S400\r\nSILENCE HAS A SEQUEL\r\nSilencio Design\r\nSilencio Technology\r\nSound Dampening Material\r\nSeamless Tempered Glass or Sound-Dampened Steel\r\nTop & Front Ventilation\r\nReversible Steel Door\r\n\r\nSERIES\r\nSilencio Series\r\nSIZE\r\nMini Tower\r\nAVAILABLE COLOR(S)\r\nBlack\r\nMATERIALS\r\nSteel, Plastic, Tempered Glass, Sound Dampening Material\r\nDIMENSIONS (LXWXH)\r\n418mm x 210mm x 408mm (incl. Protrusions), 403.5mm x 210mm x 400mm (excl. Protrusions)\r\nMOTHERBOARD SUPPORT\r\nMini ITX, Micro ATX\r\nEXPANSION SLOTS\r\n4\r\n5.25\" DRIVE BAYS\r\n1\r\n3.5\" DRIVE BAYS\r\n4\r\n2.5\" DRIVE BAYS\r\n4\r\nI/O PANEL\r\n2x USB 3.2 Gen 1 (formerly USB 3.0), 1x 3.5mm Headset Jack (Audio+Mic), 1x SD card reader\r\nPRE-INSTALLED FANS - FRONT\r\n1x 120mm (PWM 800-1400 RPM)\r\nPRE-INSTALLED FANS - REAR\r\n1x 120mm (PWM 800-1400 RPM)\r\nFAN SUPPORT - FRONT\r\n2x 120/140mm\r\nFAN SUPPORT - REAR\r\n1x 120mm\r\nRADIATOR SUPPORT - FRONT\r\n120mm, 140mm, 240mm, 280mm (remove & reinstall ODD bracket to mount 280mm radiator, may interfere with HDD mounted below ODD bracket)\r\nRADIATOR SUPPORT - TOP\r\n120mm, 240mm (requires removal of ODD cage)\r\nRADIATOR SUPPORT - REAR\r\n120mm\r\nCLEARANCE - CPU COOLER\r\nSteel: 167mm, TG: 166mm\r\nCLEARANCE - GFX\r\n319mm\r\nCLEARANCE - PSU\r\n325mm (w/o front radiator & HDD cage), 140mm (HDD cage in backmost position)\r\nPOWER SUPPLY SUPPORT\r\nBottom mount, ATX PS2\r\nDUST FILTERS\r\nTop, Front, Bottom\r\nEAN CODE\r\n4719512087381 (Steel), 4719512087374 (TG)\r\nUPC CODE\r\n884102059834 (Steel), 884102059827 (TG)\r\nCABLE ROUTING\r\n20mm\r\nFAN SUPPORT - TOP\r\n1x 120/140mm, 2x 120/140mm (remove ODD cage)'),
(21, 'Cooler Master', 'MASTERGEL MAKER', 'Pasta Termica', '70,00', 1, 'PASTATERMICA_COOLERMASTER_MASTERGELMAKER.png', 'MASTERGEL MAKER\r\nHIGH PERFORMANCE THERMAL GREASE\r\nEnhanced User Experience Design\r\nPrecise and Even\r\nHigh Conductivity to aid heat transfer\r\n\r\n'),
(45, 'ONWARE', 'Upgrade', 'Computador', '3000', 10, 'COMPUTADOR_ONWARE_UPGRADE.png', 'O PC Upgrade te da um excelente hardware com uma diversa gama de jogos em Full HD e uma possibilidade muito grande para futuros upgrades fazendo assim com que sua maquina dure anos na gameplay\r\n\r\nEspecificaÃ§Ãµes:\r\n\r\nCPU: AMD Ryzen 5 1600 6/12 3.2Ghz-3.6Ghz\r\nCooler: AMD Wraith Spire (No LED)\r\nGPU: Asus Strix RX 570 4GB GDDR5\r\nMOBO: Aorus B450M Micro ATX\r\nRAM: 1x8GB Hyperx Predator RGB DDR4 3200Ghz\r\nSSD: Kingston M.2 A2000 250GB L-3200MB/s E-2200MB/s\r\nHDD: WD Blue 2TB 5400RPM\r\nPSU: Corsair TX650M 80 Plus Gold Modular\r\nCASE: Cooler Master Q300L'),
(44, 'ONWARE', 'Invictus', 'Computador', '7000,00', 2, 'COMPUTADOR_INVICTUS_ONWARE.png', 'Linha Premium, um computador de respeito que vai levar sua jogada ao mÃ¡ximo desempenho, o Invictus foi cuidadosamente pesado para o Gamer que deseja jogar muito e nÃ£o gastar tanto, ele possui o hardware para jogar no Ultra em 2.5K e com folga, vocÃª pode desfrutar de anos de jogatina inabalÃ¡veis pelo excelente desempenho deste PC.\r\n\r\nEspecificaÃ§Ãµes:\r\n\r\nCPU: AMD Ryzen 5 3700X 8/16 3.6Ghz-4.4Ghz\r\nCooler: AMD Wraith Prism RGB\r\nGPU: Asus Strix RTX 2060 Super 8GB GDDR6\r\nMOBO: Aorus B450M Micro ATX\r\nRAM: 2x8GB Hyperx Predator RGB DDR4 3200Ghz\r\nSSD: Samsung 970 EVO Plus 500GB L-3500MB/s E-3200MB/s\r\nHDD: WD Purple 4TB 5400RPM\r\nPSU: Corsair TX650M 80 Plus Gold Modular\r\nCASE: NZXT H400I RGB');

-- --------------------------------------------------------

--
-- Estrutura da tabela `usuario`
--

DROP TABLE IF EXISTS `usuario`;
CREATE TABLE IF NOT EXISTS `usuario` (
  `id_usuario` int(11) NOT NULL AUTO_INCREMENT,
  `nome` varchar(50) DEFAULT NULL,
  `email` varchar(50) DEFAULT NULL,
  `usuario` varchar(20) DEFAULT NULL,
  `senha` varchar(220) DEFAULT NULL,
  `cpf` bigint(20) NOT NULL,
  `nasc` varchar(20) DEFAULT NULL,
  `telefone` bigint(20) DEFAULT NULL,
  `cep` bigint(20) NOT NULL,
  `endereco` varchar(220) DEFAULT NULL,
  `bairro` varchar(220) DEFAULT NULL,
  `cidade` varchar(220) DEFAULT NULL,
  `estado` varchar(220) DEFAULT NULL,
  `nivel` int(2) DEFAULT '0',
  `criado` date DEFAULT NULL,
  `modified` date DEFAULT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE KEY `cpf` (`cpf`)
) ENGINE=MyISAM AUTO_INCREMENT=8 DEFAULT CHARSET=utf8;

--
-- Extraindo dados da tabela `usuario`
--

INSERT INTO `usuario` (`id_usuario`, `nome`, `email`, `usuario`, `senha`, `cpf`, `nasc`, `telefone`, `cep`, `endereco`, `bairro`, `cidade`, `estado`, `nivel`, `criado`, `modified`) VALUES
(1, 'Giulius Cotelo', 'giulius@onware.com', 'giulius', '$2y$10$.VmTMkH3rflMZq9NrcGbSOksTVHk1LWQyOq5ZjFmeWhlUlbZTqYjy', 12375525914, '2001-12-20', 45998624155, 85813410, 'Rua Tom Jobim 370', 'Country', 'Cascavel', 'Parana', 2, NULL, NULL),
(2, 'Alcides Pereira', 'alcides@onware.com', 'alcides', '$2y$10$.VmTMkH3rflMZq9NrcGbSOksTVHk1LWQyOq5ZjFmeWhlUlbZTqYjy', 1, '2019-10-18', 4599363823, 85810240, 'Rua Rui BArbosa 611', 'Jardim Cristal', 'Cascavel', 'Parana', 2, NULL, NULL),
(3, 'Marcos Gubert', 'marcosg@onware.com', 'marcos', '$2y$10$.VmTMkH3rflMZq9NrcGbSOksTVHk1LWQyOq5ZjFmeWhlUlbZTqYjy', 2, '2019-10-18', 4599403755, 85810240, 'Rua Rui BArbosa 611', 'Jardim Cristal', 'Cascavel', 'Parana', 1, NULL, '2019-11-01'),
(4, 'Anderson Deitos', 'anderson@onware.com', 'dell', '$2y$10$.VmTMkH3rflMZq9NrcGbSOksTVHk1LWQyOq5ZjFmeWhlUlbZTqYjy', 3, '2019-10-18', 4599526319, 85810240, 'Rua Rui BArbosa 611', 'Jardim Cristal', 'Cascavel', 'Parana', 0, NULL, NULL),
(6, 'ricardo', 'teste2@gmail.com', 'teste2', '$2y$10$sgNfwLk6BK6MuEx/DEn3u.k9s46Pkoe3pQQzYatVlG.MU9LUaod6a', 21354, '254365-03-14', 214324, 13254, 'eressf', 'fdsdfsf', 'sdfsdfsfsfsd', 'fsfdfsd', 0, '2019-10-26', '2019-11-01');
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
